version: '3.8'

services:
  app:
    build: .
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
    restart: unless-stopped
    command: ['node', 'dist/main.js']
    networks:
      - expander-net

networks:
  expander-net:
    driver: bridge
